### ISSUE TITLE
Filtering may not be working 100%

### ISSUE THREAD

**Issue by Dipposh33** [statico/jsgrids#46]
If I filter by e.g. Sorting, React-Table is the first time (not react-window),  and then in the 3rd row, there is a blank React-Table? I'm assuming that the first one should be React-Window?

**Comment by statico** [comment]
Hmm, I'm not able to reproduce this. I did just refactor the filtering and the code is here if it looks good to you: https://github.com/statico/jsgrids/blob/main/components/FilterBar.tsx#L150-L172

**Comment by Dipposh33** [comment]
Hmm.  Sorry, I can't recreate it now either.  I was messing around in the console so perhaps I messed up the DOM.
